//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldToolServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVAR_Charges
    {
        public int CHARGEId { get; set; }
        public int CaseId { get; set; }
        public Nullable<int> CityEmpl_Charge { get; set; }
        public Nullable<decimal> ChargeAmount { get; set; }
        public Nullable<int> Summons_No { get; set; }
        public Nullable<System.DateTime> Trial_Time { get; set; }
    }
}
